version: "3.9"

services:
  postgres:
    container_name: postgresdb
    image: postgres:14.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234512345"
    ports:
      - "5436:5432"
    networks:
      - default

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - default

  calendar:
    container_name: calendar
    build:
      context: ..
      dockerfile: ./build/calendar/Dockerfile
    ports:
      - "8888:2345"
    networks:
      - default

  scheduler:
    container_name: scheduler
    build:
      context: ..
      dockerfile: ./build/calendar_scheduler/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - default

  sender:
    container_name: sender
    build:
      context: ..
      dockerfile: ./build/calendar_sender/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - default

networks:
  default:
    driver: bridge
