replicaCount: 2
image:
  repository: dockerhub/calendar
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: calendar.local
      paths:
        - path: /
          pathType: Prefix
