[logger]
level = "info"

[database]
Prefix       = "postgresql"
DatabaseName = "calendardb"
Host         = "localhost"
Port         = "5432"
UserName     = "postgres"
Password     = "1234512345"

[http_server]
Host = "localhost"
Port = "8080"

[grpc_server]
Host = "localhost"
Port = "9090"
