[logger]
level = "info"

[connection]
login = "guest"
password = "guest"
host = "localhost"
port = "5672"

[consume]
Queue     = "test_queue"
Consumer  = "test-consumer"
AutoAck   = true
Exclusive = false
NoLocal   = false
NoWait    = false
Interval  = "1s"

[publish]
Exchange    = "test_exchange"
Key         = "test_key"
ContentType = "application/json"
Mandatory   = false
Immediate   = false

[queue]
Name       = "test_queue"
Durable    = false
AutoDelete = false
Exclusive  = false
NoWait     = false

[database]
Prefix       = "postgresql"
DatabaseName = "calendardb"
Host         = "localhost"
Port         = "5432"
UserName     = "postgres"
Password     = "1234512345"
