[logger]
level = "info"

[connection]
login = "guest"
password = "guest"
host = "localhost"
port = "5672"

[consume]
Queue     = "test_queue"
Consumer  = "test-consumer"
AutoAck   = true
Exclusive = false
NoLocal   = false
NoWait    = false
Interval  = "1s"
