[logger]
level = "info"

[connection]
login = "guest"
password = "guest"
host = "localhost"
port = "5672"

[consume]
queue = "notification"
consumer = "q"
autoAck = true
exclusive = false
noLocal = false
noWait = false
interval = "1m"
